"use client";

import { useState } from "react";

export type CorporateAction = { id: string; symbol: string; actionType: "cash_dividend" | "split"; effectiveAt: string; ratio: number | null; cashAmount: number | null; status: "scheduled" | "applied" | "canceled"; source: string; notes: string | null };
const cash = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 4 }).format(value);

export default function CorporateActionsPanel({ actions, onRefresh, onNotice, onError }: { actions: CorporateAction[]; onRefresh: () => Promise<void>; onNotice: (message: string) => void; onError: (message: string) => void }) {
  const [symbol, setSymbol] = useState("AAPL"), [actionType, setActionType] = useState<"cash_dividend" | "split">("cash_dividend"), [effectiveDate, setEffectiveDate] = useState(new Date().toISOString().slice(0, 10)), [value, setValue] = useState("0.25"), [notes, setNotes] = useState(""), [busy, setBusy] = useState(false);
  const [renderedAt] = useState(() => Date.now());
  async function schedule() {
    setBusy(true); const response = await fetch("/api/corporate-actions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ symbol, actionType, effectiveDate, cashAmount: actionType === "cash_dividend" ? Number(value) : undefined, ratio: actionType === "split" ? Number(value) : undefined, notes }) });
    const payload = await response.json() as { error?: string }; setBusy(false); if (!response.ok) return onError(payload.error || "Unable to schedule action.");
    onNotice("Corporate action scheduled. Due actions are applied idempotently across every affected portfolio."); await onRefresh();
  }
  async function cancel(id: string) {
    const response = await fetch(`/api/corporate-actions?id=${encodeURIComponent(id)}`, { method: "DELETE" }); const payload = await response.json() as { error?: string };
    if (!response.ok) return onError(payload.error || "Unable to cancel action."); onNotice("Corporate action canceled."); await onRefresh();
  }
  return <section className="corporate-layout"><article className="panel corporate-form"><div className="panel-head"><div><span className="panel-title">Schedule simulated action</span><p>Apply a split or cash dividend to every portfolio holding the security</p></div></div><div className="corporate-fields"><label>Symbol<input value={symbol} onChange={(event) => setSymbol(event.target.value.toUpperCase())}/></label><label>Action<select value={actionType} onChange={(event) => { const next = event.target.value as typeof actionType; setActionType(next); setValue(next === "split" ? "2" : "0.25"); }}><option value="cash_dividend">Cash dividend</option><option value="split">Stock split</option></select></label><label>Effective date<input type="date" min={new Date().toISOString().slice(0, 10)} value={effectiveDate} onChange={(event) => setEffectiveDate(event.target.value)}/></label><label>{actionType === "split" ? "Split ratio" : "Amount per share"}<input type="number" min="0.0001" step="0.0001" value={value} onChange={(event) => setValue(event.target.value)}/></label><label className="corporate-notes">Notes<input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional source or event context"/></label><button className="trade-button" disabled={busy || !symbol || Number(value) <= 0} onClick={schedule}>{busy ? "Scheduling…" : "Schedule action"}</button></div><div className="lifecycle-note"><strong>Lifecycle order</strong><span>Eligible short American calls are evaluated for dividend-driven early assignment before the dividend posts. Splits adjust share lots, linked option quantities, strikes, and cost bases without changing economic value.</span></div></article><article className="panel corporate-history"><div className="panel-head"><div><span className="panel-title">Action ledger</span><p>Manual simulation source · newest effective date first</p></div></div>{actions.length ? <div className="corporate-list">{actions.map((action) => <div key={action.id}><div><strong>{action.symbol}</strong><span>{action.actionType === "split" ? `${action.ratio}:1 split` : `${cash(action.cashAmount || 0)} dividend`}</span></div><div><span className={`status-pill ${action.status}`}>{action.status}</span><small>{new Date(action.effectiveAt).toLocaleString()}</small></div>{action.status === "scheduled" && new Date(action.effectiveAt).getTime() > renderedAt ? <button className="text-button danger" onClick={() => cancel(action.id)}>Cancel</button> : <span/>}</div>)}</div> : <div className="panel-empty"><strong>No corporate actions</strong><span>Schedule a local event to test dividend, split, and assignment accounting.</span></div>}</article></section>;
}
